<?php
/**
 * @see Bluesnap_Payment_Block_Payment_Form_Cse
 * @var $this Bluesnap_Payment_Block_Payment_Form_Cse
 */
?>
<div class="tool-tip" id="payment-tool-tip" style="display:none">
    <div class="btn-close"><a href="javascript:void(0)" onclick="document.getElementById('payment-tool-tip').style.display='none';" id="payment-tool-tip-close" title="Close">Close</a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif',array('_area'=>'frontend'))?>" alt="Card Verification Number Visual Reference" title="Card Verification Number Visual Reference"></div>
</div>
<?php $_code = $this->getMethodCode() ?>
<?php $cards = $this->getCards() ?>
<?php $iFrameSrc = $this->getIframeSrc(); ?>
<?php $imgSrc = $this->getImageSrc(); ?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">

    <?php if (count($cards)): ?>
        <li>
            <ul class="saved-cc">
                <?php foreach ($this->getCards() as $id => $card): ?>
                    <li>
                        <input type="radio" name="bluesnap_card_saved" id="<?php echo $_code . '_' . $id ?>"
                               value="<?php echo $card['enc_type'] ?>" onclick="$('card-form').hide()"
                               class="validate-one-required-by-name bluesnap_card_saved"/>
                        <label for="<?php echo $_code . '_' . $id ?>"
                               style="padding-left: 10px"><?php echo $card['type'] ?>
                            -<?php echo $card['card'] ?></label>
                    </li>
                <?php endforeach ?>
                <li><a href="#"
                       onclick="$('card-form').toggle();$('no_saved_card').checked=true;return false;"><?php echo $this->__('Provide another card') ?></a>
                    <input type="radio" name="bluesnap_card_saved" id="no_saved_card" value="no" checked="checked"
                           class="validate-one-required-by-name bluesnap_card_saved" style="display:none"/>
                </li>
            </ul>
        </li>
    <?php endif ?>
    <li>
        <ul id="card-form" <?php if (count($cards)): ?>style="display:none;"<?php endif?>>
            <li>
                <label for="<?php echo $_code ?>_cc_type"
                       class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>

                <div class="input-box">
                    <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]"
                            class="required-entry validate-cc-type-select">
                        <option value=""><?php echo $this->__('--Please Select--') ?></option>
                        <?php $_ccType = $this->getInfoData('cc_type') ?>
                        <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                            <option
                                value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_number"
                       class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>

                <div class="input-box">
                </div>
                <input type="text" id="<?php echo $_code ?>_cc_number" onchange="removeSpaceCc(this)" name="payment_holder"
                       title="<?php echo $this->__('Credit Card Number') ?>"
                       class="input-text validate-cc-number validate-cc-type" data-bluesnap="encryptedCreditCard">
         
                <input type="hidden" name="<?php echo $_code ?>_cc_last" id="<?php echo $_code ?>_cc_last" value=""/>
                <input type="hidden" name="bspubkey" id="bspubkey" value='<?php echo $this->getpublicKey()?>'/>
            </li>
            <li id="<?php echo $_code ?>_cc_type_exp_div">
                <label for="<?php echo $_code ?>_expiration"
                       class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>

                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]"
                                class="month validate-cc-exp required-entry">
                            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                            <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                <option
                                    value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix">
                        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]"
                                class="year required-entry">
                            <?php foreach ($this->getCcYears() as $k => $v): ?>
                                <option
                                    value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </li>
            <?php echo $this->getChildHtml() ?>
            <?php if ($this->hasVerification()): ?>
                <li id="<?php echo $_code ?>_cc_type_cvv_div">
                    <label for="<?php echo $_code ?>_cc_cid"
                           class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>

                    <div class="input-box">
                        <div class="v-fix">
                            <input type="text" onchange="setevent();" title="<?php echo $this->__('Card Verification Number') ?>"
                                   class="input-text cvv required-entry validate-cc-cvn"
                                   id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" data-bluesnap="encryptedCvv"
                                   value=""/>
                        </div>
                        <a href="javascript:void(0)" onclick="document.getElementById('payment-tool-tip').style.display='block'" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                    </div>
                </li>
            <?php endif; ?>
        </ul>
        <iframe width="1" height="1" frameborder="0" scrolling="no" src="<?php echo $iFrameSrc ?>">
            <img width="1" height="1" src="<?php echo $imgSrc;?>">
        </iframe>
    </li>
</ul>

<style type="text/css">#payment-tool-tip{background:#FFFFFF;padding:4px;position: absolute;border: 1px solid #aaa;border-radius: 5px;}</style>