<?php
/**
 * @see Bluesnap_Payment_Block_Payment_Info_Buynow
 * @var $this Bluesnap_Payment_Block_Payment_Info_Buynow
 */
?>
<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>

<br />
<?php
echo $this->__("Credit Card last 4 digits:"). $this->getInfo()->getCcLast4();
?>
<br />
<?php
echo $this->__('Expriration Date:') . $this->getInfo()->getCcExpMonth()."/" .  $this->getInfo()->getCcExpYear();


