<?php
/**
* Template for Mage_Page_Block_Html
*/
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
    <head>
        <?php echo $this->getChildHtml('head') ?>
        <script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>

    </head>
    <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
        <div class="wrapper">
            <div class="page">
                <div class="main-container col2-left-layout">
                    <div class="main">
                        <div class="col-main">


                            <?php
                            $methods = $this->getMethods();
                            $oneMethod = count($methods) <= 1;
                            ?>
                            <?php if (empty($methods)): ?>
                                <dt>
                                    <?php echo $this->__('No Payment Methods') ?>
                                </dt>
                                <?php else:
                                foreach ($methods as $_method):
                                    $_code = $_method->getCode();
                                    ?>
                                    <dt>
                                        <?php if(!$oneMethod): ?>
                                            <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
                                        <?php else: ?>
                                        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
                                        <?php $oneMethod = $_code; ?>
                                        <?php endif; ?>
                                    <label for="p_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
                                </dt>
                                <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
                                    <dd>
                                        <?php echo $html; ?>
                                    </dd>
                                    <?php endif; ?>
                                <?php endforeach;
                            endif;
                            ?>
                            <?php echo $this->getChildChildHtml('additional'); ?>
                            <script type="text/javascript">
                                //<![CDATA[
                                <?php echo $this->getChildChildHtml('scripts'); ?>
                                payment.init();
                                <?php if (is_string($oneMethod)): ?>
                                    payment.switchMethod('<?php echo $oneMethod ?>');
                                    <?php endif; ?>
                                //]]>
                            </script>



                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>


